# Form implementation generated from reading ui file 'c:\Users\Kamguh\Documents\GitHub\pss-ttt\pss-ttt-importdialog.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ImportDialog(object):
    def setupUi(self, ImportDialog):
        ImportDialog.setObjectName("ImportDialog")
        ImportDialog.resize(327, 169)
        self.importDialogLabel = QtWidgets.QLabel(parent=ImportDialog)
        self.importDialogLabel.setGeometry(QtCore.QRect(10, 60, 311, 71))
        self.importDialogLabel.setText("")
        self.importDialogLabel.setObjectName("importDialogLabel")
        self.importFilenameBox = QtWidgets.QPlainTextEdit(parent=ImportDialog)
        self.importFilenameBox.setGeometry(QtCore.QRect(20, 20, 181, 31))
        self.importFilenameBox.setTabChangesFocus(True)
        self.importFilenameBox.setObjectName("importFilenameBox")
        self.importFilenameLabel = QtWidgets.QLabel(parent=ImportDialog)
        self.importFilenameLabel.setGeometry(QtCore.QRect(20, 0, 181, 21))
        self.importFilenameLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.importFilenameLabel.setObjectName("importFilenameLabel")
        self.importTargetsButton = QtWidgets.QPushButton(parent=ImportDialog)
        self.importTargetsButton.setGeometry(QtCore.QRect(214, 20, 101, 23))
        self.importTargetsButton.setObjectName("importTargetsButton")
        self.importProgressBar = QtWidgets.QProgressBar(parent=ImportDialog)
        self.importProgressBar.setGeometry(QtCore.QRect(10, 140, 311, 23))
        self.importProgressBar.setProperty("value", 0)
        self.importProgressBar.setObjectName("importProgressBar")

        self.retranslateUi(ImportDialog)
        QtCore.QMetaObject.connectSlotsByName(ImportDialog)

    def retranslateUi(self, ImportDialog):
        _translate = QtCore.QCoreApplication.translate
        ImportDialog.setWindowTitle(_translate("ImportDialog", "Import Targets Data"))
        self.importFilenameLabel.setText(_translate("ImportDialog", "Import file name"))
        self.importTargetsButton.setText(_translate("ImportDialog", "Import targets"))
