# Form implementation generated from reading ui file 'c:\Users\Kamguh\Documents\GitHub\pss-ttt\_internal\pss-ttt-stt.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_starTargetTracking(object):
    def setupUi(self, starTargetTracking):
        starTargetTracking.setObjectName("starTargetTracking")
        starTargetTracking.resize(400, 300)

        self.retranslateUi(starTargetTracking)
        QtCore.QMetaObject.connectSlotsByName(starTargetTracking)

    def retranslateUi(self, starTargetTracking):
        _translate = QtCore.QCoreApplication.translate
        starTargetTracking.setWindowTitle(_translate("starTargetTracking", "Dialog"))
