# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'pss-ttt.ui'
##
## Created by: Qt User Interface Compiler version 6.6.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QHeaderView, QLabel,
    QMainWindow, QMenu, QMenuBar, QPlainTextEdit,
    QPushButton, QSizePolicy, QStatusBar, QTableView,
    QTextBrowser, QTextEdit, QToolButton, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(592, 611)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QFont()
        font.setFamilies([u"Calibri"])
        MainWindow.setFont(font)
#if QT_CONFIG(statustip)
        MainWindow.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
        MainWindow.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)
        self.actionImport_Data = QAction(MainWindow)
        self.actionImport_Data.setObjectName(u"actionImport_Data")
        self.actionExport_Fights = QAction(MainWindow)
        self.actionExport_Fights.setObjectName(u"actionExport_Fights")
        self.actionTrainer = QAction(MainWindow)
        self.actionTrainer.setObjectName(u"actionTrainer")
        self.actionLoadout_Builder = QAction(MainWindow)
        self.actionLoadout_Builder.setObjectName(u"actionLoadout_Builder")
        self.actionPlanner = QAction(MainWindow)
        self.actionPlanner.setObjectName(u"actionPlanner")
        self.actionStars_Calculator = QAction(MainWindow)
        self.actionStars_Calculator.setObjectName(u"actionStars_Calculator")
        self.actionTarget_Tracking = QAction(MainWindow)
        self.actionTarget_Tracking.setObjectName(u"actionTarget_Tracking")
        self.actionAbout = QAction(MainWindow)
        self.actionAbout.setObjectName(u"actionAbout")
        self.actionDark_Mode = QAction(MainWindow)
        self.actionDark_Mode.setObjectName(u"actionDark_Mode")
        self.actionDark_Mode.setCheckable(True)
        self.actionPrestige_Calculator = QAction(MainWindow)
        self.actionPrestige_Calculator.setObjectName(u"actionPrestige_Calculator")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.fleetNameLabel = QLabel(self.centralwidget)
        self.fleetNameLabel.setObjectName(u"fleetNameLabel")
        self.fleetNameLabel.setGeometry(QRect(40, 80, 91, 16))
        font1 = QFont()
        font1.setFamilies([u"Calibri"])
        font1.setPointSize(12)
        font1.setBold(True)
        font1.setItalic(False)
        self.fleetNameLabel.setFont(font1)
        self.fleetNameLabel.setAlignment(Qt.AlignCenter)
        self.bestStars = QTextBrowser(self.centralwidget)
        self.bestStars.setObjectName(u"bestStars")
        self.bestStars.setGeometry(QRect(150, 200, 81, 31))
        self.bestStars.setTabChangesFocus(True)
        self.maxTrophiesLabel = QLabel(self.centralwidget)
        self.maxTrophiesLabel.setObjectName(u"maxTrophiesLabel")
        self.maxTrophiesLabel.setGeometry(QRect(120, 240, 131, 20))
        self.maxTrophiesLabel.setFont(font1)
        self.maxTrophiesLabel.setAlignment(Qt.AlignCenter)
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 10, 91, 16))
        self.label.setFont(font1)
        self.tournamentFightsLabel = QLabel(self.centralwidget)
        self.tournamentFightsLabel.setObjectName(u"tournamentFightsLabel")
        self.tournamentFightsLabel.setGeometry(QRect(6, 290, 191, 16))
        self.tournamentFightsLabel.setFont(font1)
        self.tournamentFightsLabel.setAlignment(Qt.AlignCenter)
        self.lastStars = QTextBrowser(self.centralwidget)
        self.lastStars.setObjectName(u"lastStars")
        self.lastStars.setGeometry(QRect(20, 200, 81, 31))
        self.lastStars.setTabChangesFocus(True)
        self.starsLastTournamentLabel = QLabel(self.centralwidget)
        self.starsLastTournamentLabel.setObjectName(u"starsLastTournamentLabel")
        self.starsLastTournamentLabel.setGeometry(QRect(20, 180, 81, 20))
        self.starsLastTournamentLabel.setFont(font1)
        self.starsLastTournamentLabel.setAlignment(Qt.AlignCenter)
        self.playerNotes = QTextEdit(self.centralwidget)
        self.playerNotes.setObjectName(u"playerNotes")
        self.playerNotes.setGeometry(QRect(240, 180, 201, 111))
        self.playerNotes.setTabChangesFocus(True)
        self.maxTrophies = QTextBrowser(self.centralwidget)
        self.maxTrophies.setObjectName(u"maxTrophies")
        self.maxTrophies.setGeometry(QRect(150, 260, 81, 31))
        self.maxTrophies.setTabChangesFocus(True)
        self.searchButton = QPushButton(self.centralwidget)
        self.searchButton.setObjectName(u"searchButton")
        self.searchButton.setGeometry(QRect(190, 10, 111, 31))
        font2 = QFont()
        font2.setFamilies([u"Calibri"])
        font2.setPointSize(9)
        font2.setBold(True)
        self.searchButton.setFont(font2)
        self.bestStarsLabel = QLabel(self.centralwidget)
        self.bestStarsLabel.setObjectName(u"bestStarsLabel")
        self.bestStarsLabel.setGeometry(QRect(150, 180, 81, 20))
        self.bestStarsLabel.setFont(font1)
        self.bestStarsLabel.setAlignment(Qt.AlignCenter)
        self.currentTrophiesLabel = QLabel(self.centralwidget)
        self.currentTrophiesLabel.setObjectName(u"currentTrophiesLabel")
        self.currentTrophiesLabel.setGeometry(QRect(-10, 240, 151, 16))
        self.currentTrophiesLabel.setFont(font1)
        self.currentTrophiesLabel.setAlignment(Qt.AlignCenter)
        self.playerNotesLabel = QLabel(self.centralwidget)
        self.playerNotesLabel.setObjectName(u"playerNotesLabel")
        self.playerNotesLabel.setGeometry(QRect(240, 160, 201, 20))
        font3 = QFont()
        font3.setFamilies([u"Calibri"])
        font3.setPointSize(12)
        font3.setBold(True)
        font3.setItalic(True)
        self.playerNotesLabel.setFont(font3)
        self.playerNotesLabel.setAlignment(Qt.AlignCenter)
        self.playerNameSearchBox = QPlainTextEdit(self.centralwidget)
        self.playerNameSearchBox.setObjectName(u"playerNameSearchBox")
        self.playerNameSearchBox.setGeometry(QRect(10, 30, 181, 31))
        font4 = QFont()
        font4.setFamilies([u"Calibri"])
        font4.setPointSize(12)
        self.playerNameSearchBox.setFont(font4)
        self.playerNameSearchBox.viewport().setProperty("cursor", QCursor(Qt.IBeamCursor))
        self.playerNameSearchBox.setFocusPolicy(Qt.StrongFocus)
        self.playerNameSearchBox.setInputMethodHints(Qt.ImhNone)
        self.playerNameSearchBox.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.playerNameSearchBox.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.playerNameSearchBox.setTabChangesFocus(True)
        self.playerNameSearchBox.setLineWrapMode(QPlainTextEdit.NoWrap)
        self.lockUnlockButton = QToolButton(self.centralwidget)
        self.lockUnlockButton.setObjectName(u"lockUnlockButton")
        self.lockUnlockButton.setGeometry(QRect(70, 140, 101, 41))
        self.lockUnlockButton.setFont(font4)
        self.lockUnlockButton.setCheckable(True)
        self.lockUnlockButton.setChecked(True)
        self.currentTrophies = QTextBrowser(self.centralwidget)
        self.currentTrophies.setObjectName(u"currentTrophies")
        self.currentTrophies.setGeometry(QRect(20, 260, 81, 31))
        self.currentTrophies.setTabChangesFocus(True)
        self.legendsFightsLabel = QLabel(self.centralwidget)
        self.legendsFightsLabel.setObjectName(u"legendsFightsLabel")
        self.legendsFightsLabel.setGeometry(QRect(200, 290, 191, 20))
        self.legendsFightsLabel.setFont(font1)
        self.legendsFightsLabel.setAlignment(Qt.AlignCenter)
        self.pvpFightsLabel = QLabel(self.centralwidget)
        self.pvpFightsLabel.setObjectName(u"pvpFightsLabel")
        self.pvpFightsLabel.setGeometry(QRect(390, 290, 191, 20))
        self.pvpFightsLabel.setFont(font1)
        self.pvpFightsLabel.setAlignment(Qt.AlignCenter)
        self.fleetName = QPlainTextEdit(self.centralwidget)
        self.fleetName.setObjectName(u"fleetName")
        self.fleetName.setGeometry(QRect(10, 100, 161, 31))
        self.fleetName.setInputMethodHints(Qt.ImhNone)
        self.fleetName.setMidLineWidth(-5)
        self.fleetName.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.fleetName.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.fleetName.setTabChangesFocus(True)
        self.fleetName.setReadOnly(False)
        self.saveNewData = QPushButton(self.centralwidget)
        self.saveNewData.setObjectName(u"saveNewData")
        self.saveNewData.setGeometry(QRect(450, 250, 111, 31))
        self.saveNewData.setFont(font2)
        self.tournyTable = QTableView(self.centralwidget)
        self.tournyTable.setObjectName(u"tournyTable")
        self.tournyTable.setGeometry(QRect(6, 310, 191, 201))
        self.legendsTable = QTableView(self.centralwidget)
        self.legendsTable.setObjectName(u"legendsTable")
        self.legendsTable.setGeometry(QRect(200, 310, 191, 201))
        self.pvpTable = QTableView(self.centralwidget)
        self.pvpTable.setObjectName(u"pvpTable")
        self.pvpTable.setGeometry(QRect(390, 310, 191, 201))
        self.pvpTable.setAlternatingRowColors(True)
        self.pvpTable.setWordWrap(False)
        self.resetButton = QPushButton(self.centralwidget)
        self.resetButton.setObjectName(u"resetButton")
        self.resetButton.setGeometry(QRect(450, 220, 111, 31))
        self.resetButton.setFont(font2)
        self.pixyshipLayoutButton = QPushButton(self.centralwidget)
        self.pixyshipLayoutButton.setObjectName(u"pixyshipLayoutButton")
        self.pixyshipLayoutButton.setGeometry(QRect(450, 190, 111, 31))
        self.pixyshipLayoutButton.setFont(font2)
        self.fleetSearchButton = QPushButton(self.centralwidget)
        self.fleetSearchButton.setObjectName(u"fleetSearchButton")
        self.fleetSearchButton.setGeometry(QRect(170, 80, 101, 31))
        self.fleetSearchButton.setFont(font2)
        self.delTournyButton = QPushButton(self.centralwidget)
        self.delTournyButton.setObjectName(u"delTournyButton")
        self.delTournyButton.setGeometry(QRect(20, 550, 151, 23))
        self.delLegendsButton = QPushButton(self.centralwidget)
        self.delLegendsButton.setObjectName(u"delLegendsButton")
        self.delLegendsButton.setGeometry(QRect(220, 550, 151, 23))
        self.delPVPButton = QPushButton(self.centralwidget)
        self.delPVPButton.setObjectName(u"delPVPButton")
        self.delPVPButton.setGeometry(QRect(410, 550, 151, 23))
        self.playerBrowserSearchButton = QPushButton(self.centralwidget)
        self.playerBrowserSearchButton.setObjectName(u"playerBrowserSearchButton")
        self.playerBrowserSearchButton.setGeometry(QRect(190, 40, 111, 31))
        self.playerBrowserSearchButton.setFont(font2)
        self.submitNewDataButton = QPushButton(self.centralwidget)
        self.submitNewDataButton.setObjectName(u"submitNewDataButton")
        self.submitNewDataButton.setGeometry(QRect(20, 520, 551, 23))
        self.fleetBrowserSearchButton = QPushButton(self.centralwidget)
        self.fleetBrowserSearchButton.setObjectName(u"fleetBrowserSearchButton")
        self.fleetBrowserSearchButton.setGeometry(QRect(170, 110, 111, 31))
        self.fleetBrowserSearchButton.setFont(font2)
        self.profileComboBox = QComboBox(self.centralwidget)
        self.profileComboBox.setObjectName(u"profileComboBox")
        self.profileComboBox.setGeometry(QRect(380, 60, 161, 22))
        self.createNewProfile = QPushButton(self.centralwidget)
        self.createNewProfile.setObjectName(u"createNewProfile")
        self.createNewProfile.setGeometry(QRect(380, 90, 75, 23))
        font5 = QFont()
        font5.setPointSize(9)
        font5.setBold(True)
        self.createNewProfile.setFont(font5)
        self.deleteSelectedProfile = QPushButton(self.centralwidget)
        self.deleteSelectedProfile.setObjectName(u"deleteSelectedProfile")
        self.deleteSelectedProfile.setGeometry(QRect(470, 90, 75, 23))
        self.deleteSelectedProfile.setFont(font5)
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(380, 40, 161, 20))
        self.label_2.setFont(font5)
        self.label_2.setAlignment(Qt.AlignCenter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        self.statusbar.setSizeGripEnabled(True)
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QMenuBar(MainWindow)
        self.menuBar.setObjectName(u"menuBar")
        self.menuBar.setGeometry(QRect(0, 0, 592, 21))
        self.menuData = QMenu(self.menuBar)
        self.menuData.setObjectName(u"menuData")
        self.menuCrew = QMenu(self.menuBar)
        self.menuCrew.setObjectName(u"menuCrew")
        self.menuTournament = QMenu(self.menuBar)
        self.menuTournament.setObjectName(u"menuTournament")
        self.menuAbout = QMenu(self.menuBar)
        self.menuAbout.setObjectName(u"menuAbout")
        MainWindow.setMenuBar(self.menuBar)
        QWidget.setTabOrder(self.playerNameSearchBox, self.searchButton)
        QWidget.setTabOrder(self.searchButton, self.fleetName)
        QWidget.setTabOrder(self.fleetName, self.fleetSearchButton)
        QWidget.setTabOrder(self.fleetSearchButton, self.lockUnlockButton)
        QWidget.setTabOrder(self.lockUnlockButton, self.lastStars)
        QWidget.setTabOrder(self.lastStars, self.bestStars)
        QWidget.setTabOrder(self.bestStars, self.currentTrophies)
        QWidget.setTabOrder(self.currentTrophies, self.maxTrophies)
        QWidget.setTabOrder(self.maxTrophies, self.playerNotes)
        QWidget.setTabOrder(self.playerNotes, self.saveNewData)
        QWidget.setTabOrder(self.saveNewData, self.resetButton)
        QWidget.setTabOrder(self.resetButton, self.submitNewDataButton)
        QWidget.setTabOrder(self.submitNewDataButton, self.tournyTable)
        QWidget.setTabOrder(self.tournyTable, self.delTournyButton)
        QWidget.setTabOrder(self.delTournyButton, self.legendsTable)
        QWidget.setTabOrder(self.legendsTable, self.delLegendsButton)
        QWidget.setTabOrder(self.delLegendsButton, self.pvpTable)
        QWidget.setTabOrder(self.pvpTable, self.delPVPButton)
        QWidget.setTabOrder(self.delPVPButton, self.pixyshipLayoutButton)
        QWidget.setTabOrder(self.pixyshipLayoutButton, self.fleetBrowserSearchButton)
        QWidget.setTabOrder(self.fleetBrowserSearchButton, self.playerBrowserSearchButton)

        self.menuBar.addAction(self.menuData.menuAction())
        self.menuBar.addAction(self.menuCrew.menuAction())
        self.menuBar.addAction(self.menuTournament.menuAction())
        self.menuBar.addAction(self.menuAbout.menuAction())
        self.menuData.addAction(self.actionImport_Data)
        self.menuData.addAction(self.actionExport_Fights)
        self.menuCrew.addAction(self.actionTrainer)
        self.menuCrew.addAction(self.actionLoadout_Builder)
        self.menuCrew.addAction(self.actionPlanner)
        self.menuCrew.addAction(self.actionPrestige_Calculator)
        self.menuTournament.addAction(self.actionStars_Calculator)
        self.menuTournament.addAction(self.actionTarget_Tracking)
        self.menuAbout.addAction(self.actionAbout)
        self.menuAbout.addAction(self.actionDark_Mode)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Pixel Starships Target Tracking Tool", None))
        self.actionImport_Data.setText(QCoreApplication.translate("MainWindow", u"Import Data", None))
        self.actionExport_Fights.setText(QCoreApplication.translate("MainWindow", u"Export Fights", None))
        self.actionTrainer.setText(QCoreApplication.translate("MainWindow", u"Trainer", None))
        self.actionLoadout_Builder.setText(QCoreApplication.translate("MainWindow", u"Loadout Builder (Beta)", None))
        self.actionPlanner.setText(QCoreApplication.translate("MainWindow", u"Planner (NOT IMPLEMENTED)", None))
        self.actionStars_Calculator.setText(QCoreApplication.translate("MainWindow", u"Stars Calculator", None))
        self.actionTarget_Tracking.setText(QCoreApplication.translate("MainWindow", u"Target Tracking", None))
        self.actionAbout.setText(QCoreApplication.translate("MainWindow", u"About", None))
        self.actionDark_Mode.setText(QCoreApplication.translate("MainWindow", u"Dark Mode", None))
        self.actionPrestige_Calculator.setText(QCoreApplication.translate("MainWindow", u"Prestige Calculator (NOT IMPLEMENTED)", None))
        self.fleetNameLabel.setText(QCoreApplication.translate("MainWindow", u"Fleet", None))
        self.maxTrophiesLabel.setText(QCoreApplication.translate("MainWindow", u"Max Trophies", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Player Name", None))
        self.tournamentFightsLabel.setText(QCoreApplication.translate("MainWindow", u"Tournament Fights", None))
        self.starsLastTournamentLabel.setText(QCoreApplication.translate("MainWindow", u"Last Stars", None))
        self.searchButton.setText(QCoreApplication.translate("MainWindow", u"Search", None))
        self.bestStarsLabel.setText(QCoreApplication.translate("MainWindow", u"Best Stars", None))
        self.currentTrophiesLabel.setText(QCoreApplication.translate("MainWindow", u"Current Trophies", None))
        self.playerNotesLabel.setText(QCoreApplication.translate("MainWindow", u"Notes", None))
        self.lockUnlockButton.setText(QCoreApplication.translate("MainWindow", u"Locked", None))
        self.legendsFightsLabel.setText(QCoreApplication.translate("MainWindow", u"Legends League Fights", None))
        self.pvpFightsLabel.setText(QCoreApplication.translate("MainWindow", u"PvP Fights", None))
        self.saveNewData.setText(QCoreApplication.translate("MainWindow", u"Save Data", None))
        self.resetButton.setText(QCoreApplication.translate("MainWindow", u"Reset Search", None))
        self.pixyshipLayoutButton.setText(QCoreApplication.translate("MainWindow", u"PixyShip Layout", None))
        self.fleetSearchButton.setText(QCoreApplication.translate("MainWindow", u"Fleet Search", None))
        self.delTournyButton.setText(QCoreApplication.translate("MainWindow", u"Delete Tournament Entry", None))
        self.delLegendsButton.setText(QCoreApplication.translate("MainWindow", u"Delete Legends Entry", None))
        self.delPVPButton.setText(QCoreApplication.translate("MainWindow", u"Delete Pvp Entry", None))
        self.playerBrowserSearchButton.setText(QCoreApplication.translate("MainWindow", u"Search Browser", None))
        self.submitNewDataButton.setText(QCoreApplication.translate("MainWindow", u"Submit Fight Data", None))
        self.fleetBrowserSearchButton.setText(QCoreApplication.translate("MainWindow", u"Search Browser", None))
        self.createNewProfile.setText(QCoreApplication.translate("MainWindow", u"New Profile", None))
        self.deleteSelectedProfile.setText(QCoreApplication.translate("MainWindow", u"Delete Profile", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Ship Profiles", None))
        self.menuData.setTitle(QCoreApplication.translate("MainWindow", u"Data", None))
        self.menuCrew.setTitle(QCoreApplication.translate("MainWindow", u"Crew", None))
        self.menuTournament.setTitle(QCoreApplication.translate("MainWindow", u"Tournament", None))
        self.menuAbout.setTitle(QCoreApplication.translate("MainWindow", u"About", None))
    # retranslateUi

