# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'pss-ttt-clb.ui'
##
## Created by: Qt User Interface Compiler version 6.6.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QDialog, QDoubleSpinBox,
    QHeaderView, QLabel, QLineEdit, QPushButton,
    QSizePolicy, QTableView, QWidget)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(557, 427)
        self.bodyEquipLabel = QLabel(Dialog)
        self.bodyEquipLabel.setObjectName(u"bodyEquipLabel")
        self.bodyEquipLabel.setGeometry(QRect(10, 40, 51, 31))
        self.headEquipLabel = QLabel(Dialog)
        self.headEquipLabel.setObjectName(u"headEquipLabel")
        self.headEquipLabel.setGeometry(QRect(10, 100, 51, 31))
        self.bodyEquipBox = QLineEdit(Dialog)
        self.bodyEquipBox.setObjectName(u"bodyEquipBox")
        self.bodyEquipBox.setGeometry(QRect(70, 40, 211, 31))
        self.headEquipBox = QLineEdit(Dialog)
        self.headEquipBox.setObjectName(u"headEquipBox")
        self.headEquipBox.setGeometry(QRect(70, 100, 211, 31))
        self.crewNameBox = QLineEdit(Dialog)
        self.crewNameBox.setObjectName(u"crewNameBox")
        self.crewNameBox.setGeometry(QRect(70, 9, 171, 21))
        self.loadCrewDataButton = QPushButton(Dialog)
        self.loadCrewDataButton.setObjectName(u"loadCrewDataButton")
        self.loadCrewDataButton.setGeometry(QRect(240, 10, 51, 23))
        self.legEquipLabel = QLabel(Dialog)
        self.legEquipLabel.setObjectName(u"legEquipLabel")
        self.legEquipLabel.setGeometry(QRect(10, 160, 51, 31))
        self.accessEquipBox = QLineEdit(Dialog)
        self.accessEquipBox.setObjectName(u"accessEquipBox")
        self.accessEquipBox.setGeometry(QRect(70, 220, 211, 31))
        self.accEquipLabel = QLabel(Dialog)
        self.accEquipLabel.setObjectName(u"accEquipLabel")
        self.accEquipLabel.setGeometry(QRect(10, 220, 61, 31))
        self.legEquipBox = QLineEdit(Dialog)
        self.legEquipBox.setObjectName(u"legEquipBox")
        self.legEquipBox.setGeometry(QRect(70, 160, 211, 31))
        self.wepEquipLabel = QLabel(Dialog)
        self.wepEquipLabel.setObjectName(u"wepEquipLabel")
        self.wepEquipLabel.setGeometry(QRect(10, 280, 61, 31))
        self.petEquipBox = QLineEdit(Dialog)
        self.petEquipBox.setObjectName(u"petEquipBox")
        self.petEquipBox.setGeometry(QRect(70, 340, 211, 31))
        self.petEquipLabel = QLabel(Dialog)
        self.petEquipLabel.setObjectName(u"petEquipLabel")
        self.petEquipLabel.setGeometry(QRect(10, 340, 51, 31))
        self.wepEquipBox = QLineEdit(Dialog)
        self.wepEquipBox.setObjectName(u"wepEquipBox")
        self.wepEquipBox.setGeometry(QRect(70, 280, 211, 31))
        self.crewTPTable = QTableView(Dialog)
        self.crewTPTable.setObjectName(u"crewTPTable")
        self.crewTPTable.setGeometry(QRect(300, 10, 81, 301))
        self.crewTPTable.setAlternatingRowColors(True)
        self.label_7 = QLabel(Dialog)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(0, 0, 71, 31))
        self.petHeroSideDD = QComboBox(Dialog)
        self.petHeroSideDD.addItem("")
        self.petHeroSideDD.addItem("")
        self.petHeroSideDD.addItem("")
        self.petHeroSideDD.addItem("")
        self.petHeroSideDD.addItem("")
        self.petHeroSideDD.addItem("")
        self.petHeroSideDD.addItem("")
        self.petHeroSideDD.addItem("")
        self.petHeroSideDD.addItem("")
        self.petHeroSideDD.addItem("")
        self.petHeroSideDD.setObjectName(u"petHeroSideDD")
        self.petHeroSideDD.setGeometry(QRect(70, 370, 91, 22))
        self.petHeroSideStat = QDoubleSpinBox(Dialog)
        self.petHeroSideStat.setObjectName(u"petHeroSideStat")
        self.petHeroSideStat.setGeometry(QRect(180, 370, 62, 22))
        self.petHeroSideStat.setDecimals(1)
        self.wepHeroSideDD = QComboBox(Dialog)
        self.wepHeroSideDD.addItem("")
        self.wepHeroSideDD.addItem("")
        self.wepHeroSideDD.addItem("")
        self.wepHeroSideDD.addItem("")
        self.wepHeroSideDD.addItem("")
        self.wepHeroSideDD.addItem("")
        self.wepHeroSideDD.addItem("")
        self.wepHeroSideDD.addItem("")
        self.wepHeroSideDD.addItem("")
        self.wepHeroSideDD.addItem("")
        self.wepHeroSideDD.setObjectName(u"wepHeroSideDD")
        self.wepHeroSideDD.setGeometry(QRect(70, 310, 91, 22))
        self.wepHeroSideStat = QDoubleSpinBox(Dialog)
        self.wepHeroSideStat.setObjectName(u"wepHeroSideStat")
        self.wepHeroSideStat.setGeometry(QRect(180, 310, 62, 22))
        self.wepHeroSideStat.setDecimals(1)
        self.accHeroSideDD = QComboBox(Dialog)
        self.accHeroSideDD.addItem("")
        self.accHeroSideDD.addItem("")
        self.accHeroSideDD.addItem("")
        self.accHeroSideDD.addItem("")
        self.accHeroSideDD.addItem("")
        self.accHeroSideDD.addItem("")
        self.accHeroSideDD.addItem("")
        self.accHeroSideDD.addItem("")
        self.accHeroSideDD.addItem("")
        self.accHeroSideDD.addItem("")
        self.accHeroSideDD.setObjectName(u"accHeroSideDD")
        self.accHeroSideDD.setGeometry(QRect(70, 250, 91, 22))
        self.accHeroSideStat = QDoubleSpinBox(Dialog)
        self.accHeroSideStat.setObjectName(u"accHeroSideStat")
        self.accHeroSideStat.setGeometry(QRect(180, 250, 62, 22))
        self.accHeroSideStat.setDecimals(1)
        self.legHeroSideDD = QComboBox(Dialog)
        self.legHeroSideDD.addItem("")
        self.legHeroSideDD.addItem("")
        self.legHeroSideDD.addItem("")
        self.legHeroSideDD.addItem("")
        self.legHeroSideDD.addItem("")
        self.legHeroSideDD.addItem("")
        self.legHeroSideDD.addItem("")
        self.legHeroSideDD.addItem("")
        self.legHeroSideDD.addItem("")
        self.legHeroSideDD.addItem("")
        self.legHeroSideDD.setObjectName(u"legHeroSideDD")
        self.legHeroSideDD.setGeometry(QRect(70, 190, 91, 22))
        self.legHeroSideStat = QDoubleSpinBox(Dialog)
        self.legHeroSideStat.setObjectName(u"legHeroSideStat")
        self.legHeroSideStat.setGeometry(QRect(180, 190, 62, 22))
        self.legHeroSideStat.setDecimals(1)
        self.headHeroSideDD = QComboBox(Dialog)
        self.headHeroSideDD.addItem("")
        self.headHeroSideDD.addItem("")
        self.headHeroSideDD.addItem("")
        self.headHeroSideDD.addItem("")
        self.headHeroSideDD.addItem("")
        self.headHeroSideDD.addItem("")
        self.headHeroSideDD.addItem("")
        self.headHeroSideDD.addItem("")
        self.headHeroSideDD.addItem("")
        self.headHeroSideDD.addItem("")
        self.headHeroSideDD.setObjectName(u"headHeroSideDD")
        self.headHeroSideDD.setGeometry(QRect(70, 130, 91, 22))
        self.headHeroSideStat = QDoubleSpinBox(Dialog)
        self.headHeroSideStat.setObjectName(u"headHeroSideStat")
        self.headHeroSideStat.setGeometry(QRect(180, 130, 62, 22))
        self.headHeroSideStat.setDecimals(1)
        self.bodyHeroSideDD = QComboBox(Dialog)
        self.bodyHeroSideDD.addItem("")
        self.bodyHeroSideDD.addItem("")
        self.bodyHeroSideDD.addItem("")
        self.bodyHeroSideDD.addItem("")
        self.bodyHeroSideDD.addItem("")
        self.bodyHeroSideDD.addItem("")
        self.bodyHeroSideDD.addItem("")
        self.bodyHeroSideDD.addItem("")
        self.bodyHeroSideDD.addItem("")
        self.bodyHeroSideDD.addItem("")
        self.bodyHeroSideDD.setObjectName(u"bodyHeroSideDD")
        self.bodyHeroSideDD.setGeometry(QRect(70, 70, 91, 22))
        self.bodyHeroSideStat = QDoubleSpinBox(Dialog)
        self.bodyHeroSideStat.setObjectName(u"bodyHeroSideStat")
        self.bodyHeroSideStat.setGeometry(QRect(180, 70, 62, 22))
        self.bodyHeroSideStat.setDecimals(1)
        self.finalTableStats = QTableView(Dialog)
        self.finalTableStats.setObjectName(u"finalTableStats")
        self.finalTableStats.setGeometry(QRect(410, 10, 141, 391))
        self.maxTPLabel = QLabel(Dialog)
        self.maxTPLabel.setObjectName(u"maxTPLabel")
        self.maxTPLabel.setGeometry(QRect(300, 320, 81, 16))

        self.retranslateUi(Dialog)

        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"Crew Loadout Builder", None))
        self.bodyEquipLabel.setText(QCoreApplication.translate("Dialog", u"Body", None))
        self.headEquipLabel.setText(QCoreApplication.translate("Dialog", u"Head", None))
        self.loadCrewDataButton.setText(QCoreApplication.translate("Dialog", u"Load", None))
        self.legEquipLabel.setText(QCoreApplication.translate("Dialog", u"Leg", None))
        self.accEquipLabel.setText(QCoreApplication.translate("Dialog", u"Accessory", None))
        self.wepEquipLabel.setText(QCoreApplication.translate("Dialog", u"Weapon", None))
        self.petEquipLabel.setText(QCoreApplication.translate("Dialog", u"Pet", None))
        self.label_7.setText(QCoreApplication.translate("Dialog", u"Crew Name", None))
        self.petHeroSideDD.setItemText(0, QCoreApplication.translate("Dialog", u"HP", None))
        self.petHeroSideDD.setItemText(1, QCoreApplication.translate("Dialog", u"Attack", None))
        self.petHeroSideDD.setItemText(2, QCoreApplication.translate("Dialog", u"Repair", None))
        self.petHeroSideDD.setItemText(3, QCoreApplication.translate("Dialog", u"Ability", None))
        self.petHeroSideDD.setItemText(4, QCoreApplication.translate("Dialog", u"Stamina", None))
        self.petHeroSideDD.setItemText(5, QCoreApplication.translate("Dialog", u"Pilot", None))
        self.petHeroSideDD.setItemText(6, QCoreApplication.translate("Dialog", u"Science", None))
        self.petHeroSideDD.setItemText(7, QCoreApplication.translate("Dialog", u"Engine", None))
        self.petHeroSideDD.setItemText(8, QCoreApplication.translate("Dialog", u"Weapon", None))
        self.petHeroSideDD.setItemText(9, QCoreApplication.translate("Dialog", u"RST", None))

        self.wepHeroSideDD.setItemText(0, QCoreApplication.translate("Dialog", u"HP", None))
        self.wepHeroSideDD.setItemText(1, QCoreApplication.translate("Dialog", u"Attack", None))
        self.wepHeroSideDD.setItemText(2, QCoreApplication.translate("Dialog", u"Repair", None))
        self.wepHeroSideDD.setItemText(3, QCoreApplication.translate("Dialog", u"Ability", None))
        self.wepHeroSideDD.setItemText(4, QCoreApplication.translate("Dialog", u"Stamina", None))
        self.wepHeroSideDD.setItemText(5, QCoreApplication.translate("Dialog", u"Pilot", None))
        self.wepHeroSideDD.setItemText(6, QCoreApplication.translate("Dialog", u"Science", None))
        self.wepHeroSideDD.setItemText(7, QCoreApplication.translate("Dialog", u"Engine", None))
        self.wepHeroSideDD.setItemText(8, QCoreApplication.translate("Dialog", u"Weapon", None))
        self.wepHeroSideDD.setItemText(9, QCoreApplication.translate("Dialog", u"RST", None))

        self.accHeroSideDD.setItemText(0, QCoreApplication.translate("Dialog", u"HP", None))
        self.accHeroSideDD.setItemText(1, QCoreApplication.translate("Dialog", u"Attack", None))
        self.accHeroSideDD.setItemText(2, QCoreApplication.translate("Dialog", u"Repair", None))
        self.accHeroSideDD.setItemText(3, QCoreApplication.translate("Dialog", u"Ability", None))
        self.accHeroSideDD.setItemText(4, QCoreApplication.translate("Dialog", u"Stamina", None))
        self.accHeroSideDD.setItemText(5, QCoreApplication.translate("Dialog", u"Pilot", None))
        self.accHeroSideDD.setItemText(6, QCoreApplication.translate("Dialog", u"Science", None))
        self.accHeroSideDD.setItemText(7, QCoreApplication.translate("Dialog", u"Engine", None))
        self.accHeroSideDD.setItemText(8, QCoreApplication.translate("Dialog", u"Weapon", None))
        self.accHeroSideDD.setItemText(9, QCoreApplication.translate("Dialog", u"RST", None))

        self.legHeroSideDD.setItemText(0, QCoreApplication.translate("Dialog", u"HP", None))
        self.legHeroSideDD.setItemText(1, QCoreApplication.translate("Dialog", u"Attack", None))
        self.legHeroSideDD.setItemText(2, QCoreApplication.translate("Dialog", u"Repair", None))
        self.legHeroSideDD.setItemText(3, QCoreApplication.translate("Dialog", u"Ability", None))
        self.legHeroSideDD.setItemText(4, QCoreApplication.translate("Dialog", u"Stamina", None))
        self.legHeroSideDD.setItemText(5, QCoreApplication.translate("Dialog", u"Pilot", None))
        self.legHeroSideDD.setItemText(6, QCoreApplication.translate("Dialog", u"Science", None))
        self.legHeroSideDD.setItemText(7, QCoreApplication.translate("Dialog", u"Engine", None))
        self.legHeroSideDD.setItemText(8, QCoreApplication.translate("Dialog", u"Weapon", None))
        self.legHeroSideDD.setItemText(9, QCoreApplication.translate("Dialog", u"RST", None))

        self.headHeroSideDD.setItemText(0, QCoreApplication.translate("Dialog", u"HP", None))
        self.headHeroSideDD.setItemText(1, QCoreApplication.translate("Dialog", u"Attack", None))
        self.headHeroSideDD.setItemText(2, QCoreApplication.translate("Dialog", u"Repair", None))
        self.headHeroSideDD.setItemText(3, QCoreApplication.translate("Dialog", u"Ability", None))
        self.headHeroSideDD.setItemText(4, QCoreApplication.translate("Dialog", u"Stamina", None))
        self.headHeroSideDD.setItemText(5, QCoreApplication.translate("Dialog", u"Pilot", None))
        self.headHeroSideDD.setItemText(6, QCoreApplication.translate("Dialog", u"Science", None))
        self.headHeroSideDD.setItemText(7, QCoreApplication.translate("Dialog", u"Engine", None))
        self.headHeroSideDD.setItemText(8, QCoreApplication.translate("Dialog", u"Weapon", None))
        self.headHeroSideDD.setItemText(9, QCoreApplication.translate("Dialog", u"RST", None))

        self.bodyHeroSideDD.setItemText(0, QCoreApplication.translate("Dialog", u"HP", None))
        self.bodyHeroSideDD.setItemText(1, QCoreApplication.translate("Dialog", u"Attack", None))
        self.bodyHeroSideDD.setItemText(2, QCoreApplication.translate("Dialog", u"Repair", None))
        self.bodyHeroSideDD.setItemText(3, QCoreApplication.translate("Dialog", u"Ability", None))
        self.bodyHeroSideDD.setItemText(4, QCoreApplication.translate("Dialog", u"Stamina", None))
        self.bodyHeroSideDD.setItemText(5, QCoreApplication.translate("Dialog", u"Pilot", None))
        self.bodyHeroSideDD.setItemText(6, QCoreApplication.translate("Dialog", u"Science", None))
        self.bodyHeroSideDD.setItemText(7, QCoreApplication.translate("Dialog", u"Engine", None))
        self.bodyHeroSideDD.setItemText(8, QCoreApplication.translate("Dialog", u"Weapon", None))
        self.bodyHeroSideDD.setItemText(9, QCoreApplication.translate("Dialog", u"RST", None))

        self.maxTPLabel.setText(QCoreApplication.translate("Dialog", u"TextLabel", None))
    # retranslateUi

